insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name, created_At) values ('Computers', NOW());
insert into tb_category (name, created_At) values ('Music', NOW());
insert into tb_category (name, created_At) values ('Camera & Photo', NOW());
insert into tb_category (name, created_At) values ('Home Audio', NOW());
insert into tb_category (name, created_At) values ('Smart Home', NOW());
insert into tb_category (name, created_At) values ('Arts & Crafts', NOW());
insert into tb_category (name, created_At) values ('Automotive', NOW());
insert into tb_category (name, created_At) values ('Baby', NOW());
insert into tb_category (name, created_At) values ('Beauty & Personal Care', NOW());
insert into tb_category (name, created_At) values ('Fashion', NOW());
insert into tb_category (name, created_At) values ('Health and Household', NOW());
insert into tb_category (name, created_At) values ('Home and Kitchen', NOW());
insert into tb_category (name, created_At) values ('Luggage', NOW());
insert into tb_category (name, created_At) values ('Movies & Television', NOW());
insert into tb_category (name, created_At) values ('Pet Supplies', NOW());
insert into tb_category (name, created_At) values ('Software', NOW());
insert into tb_category (name, created_At) values ('Sports', NOW());
insert into tb_category (name, created_At) values ('Tools', NOW());
insert into tb_category (name, created_At) values ('Toys', NOW());
insert into tb_category (name, created_At) values ('Games', NOW());
insert into tb_category (name, created_At) values ('Music', NOW());
insert into tb_category (name, created_At) values ('Camera & Photo', NOW());
insert into tb_category (name, created_At) values ('Home Audio', NOW());
insert into tb_category (name, created_At) values ('Smart Home', NOW());
insert into tb_category (name, created_At) values ('Arts & Crafts', NOW());
insert into tb_category (name, created_At) values ('Automotive', NOW());
insert into tb_category (name, created_At) values ('Baby', NOW());
insert into tb_category (name, created_At) values ('Beauty & Personal Care', NOW());
insert into tb_category (name, created_At) values ('Fashion', NOW());
insert into tb_category (name, created_At) values ('Health and Household', NOW());
insert into tb_category (name, created_At) values ('Home and Kitchen', NOW());
insert into tb_category (name, created_At) values ('Luggage', NOW());
insert into tb_category (name, created_At) values ('Movies & Television', NOW());
insert into tb_category (name, created_At) values ('Pet Supplies', NOW());
insert into tb_category (name, created_At) values ('Software', NOW());
insert into tb_category (name, created_At) values ('Sports', NOW());
insert into tb_category (name, created_At) values ('Tools', NOW());
insert into tb_category (name, created_At) values ('Toys', NOW());
